[DS-631] feat: Create component to render custom modals
eduNEXT/frontend-app-validation-panel pull request #2
Opened 2023-08-24 20:54 UTC by bra-i-am

* Add possibility of using it with or without tabs

2023-08-25 13:33 UTC, dcoa commented
don't forget to follow this directory structure https://github.com/eduNEXT/frontend-app-validation-panel/blob/master/docs/decisions/0002-feature-based-application-organization.rst#file-and-directory-naming 

so create an index.jsx file , please.

Should this PR depend on the other one?

2023-08-28 00:11 UTC, dcoa requested changes
Just that small changes and I can approve it.

2023-08-28 00:11 UTC, dcoa commented on src/components/ModalLayout/index.js
> +export { default as ModalLayout } from './ModalLayout';
```suggestion
export { default } from './ModalLayout';
```

2023-08-28 00:11 UTC, dcoa commented on src/components/index.js
I don't think this file is necessary.

2023-08-28 00:14 UTC, dcoa commented on src/components/ModalLayout/ModalLayout.jsx
> +import PropTypes from 'prop-types';
Take in mind the import order

2023-08-28 00:25 UTC, dcoa commented on src/components/ModalLayout/ModalLayout.jsx
> +      {!!tabs.length
I think the tabs should be part of the Modal body instead of the header.

2023-08-28 13:33 UTC, bra-i-am commented on src/components/ModalLayout/index.js
> +export { default as ModalLayout } from './ModalLayout';
I tried the change but now there's an error with eslint:

`'default' is restricted from being used as an exported name.`

2023-08-28 13:46 UTC, bra-i-am commented on src/components/index.js
Following the example of [A module with a sub-module](https://github.com/eduNEXT/frontend-app-validation-panel/blob/master/docs/decisions/0002-feature-based-application-organization.rst#file-and-directory-naming:~:text=A%20module%20with%20a%20sub%2Dmodule%3A), it uses a public interface not only for the main feature but also for the sub-components, that's the why I created it, but you're right. Change applied.

2023-08-29 12:56 UTC, dcoa approved these changes

2023-08-29 20:40 UTC, merged